### ISSUE TITLE
Consider the relicensing to BSD-2-Clause

### ISSUE THREAD

**Issue by jserv** [linD026/mthpc#1]
Quote from [FreeBSD Licensing Policy](https://docs.freebsd.org/en/articles/license-guide/)
> The FreeBSD project does not allow using the "advertising clause" in new code. Due to the large number of contributors to the FreeBSD project, complying with this clause for many commercial vendors has become difficult. If you have code in the tree with the advertising clause, please consider switching to a license without it. New contributions to FreeBSD should use the BSD-2-Clause license.

The transition from 3-clause BSD License to BSD-2-Clause is to get rid of "advertising clause," making it more friendly for commercial adoptions. It would be great if this project can be relicensed for the similar considerations.

**Comment by linD026** [comment]
Sure.
Now the license is the same as  [FTC's](https://github.com/linD026/Function-grained-Task-Control/commit/a2ad976e524b20fb1a44d2beff4d5af2ae1bdcf9).
Thanks for the suggestion.
